/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokensRouteImport } from './routes/tokens'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PerpsRouteImport } from './routes/perps'
import { Route as MemesRouteImport } from './routes/memes'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssetIdentifierRouteImport } from './routes/asset.$identifier'
import { Route as ApiHyperliquidRouteImport } from './routes/api/hyperliquid'
import { Route as ApiCodexRouteImport } from './routes/api/codex'
import { Route as ApiPolymarketOrderRouteImport } from './routes/api/polymarket/order'
import { Route as ApiPolymarketHistoryRouteImport } from './routes/api/polymarket/history'
import { Route as ApiPolymarketEventsRouteImport } from './routes/api/polymarket/events'
import { Route as ApiPolymarketDeriveCredsRouteImport } from './routes/api/polymarket/derive-creds'
import { Route as ApiGeckoterminalTokenDetailRouteImport } from './routes/api/geckoterminal/token-detail'
import { Route as ApiGeckoterminalOhlcvRouteImport } from './routes/api/geckoterminal/ohlcv'
import { Route as ApiGeckoterminalMemesRouteImport } from './routes/api/geckoterminal/memes'
import { Route as ApiCodexTokenRouteImport } from './routes/api/codex/token'
import { Route as ApiCodexBaseTokensRouteImport } from './routes/api/codex/base-tokens'
import { Route as ApiCodexBarsRouteImport } from './routes/api/codex/bars'

const TokensRoute = TokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PerpsRoute = PerpsRouteImport.update({
  id: '/perps',
  path: '/perps',
  getParentRoute: () => rootRouteImport,
} as any)
const MemesRoute = MemesRouteImport.update({
  id: '/memes',
  path: '/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetIdentifierRoute = AssetIdentifierRouteImport.update({
  id: '/asset/$identifier',
  path: '/asset/$identifier',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHyperliquidRoute = ApiHyperliquidRouteImport.update({
  id: '/api/hyperliquid',
  path: '/api/hyperliquid',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexRoute = ApiCodexRouteImport.update({
  id: '/api/codex',
  path: '/api/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketOrderRoute = ApiPolymarketOrderRouteImport.update({
  id: '/api/polymarket/order',
  path: '/api/polymarket/order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketHistoryRoute = ApiPolymarketHistoryRouteImport.update({
  id: '/api/polymarket/history',
  path: '/api/polymarket/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketEventsRoute = ApiPolymarketEventsRouteImport.update({
  id: '/api/polymarket/events',
  path: '/api/polymarket/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPolymarketDeriveCredsRoute =
  ApiPolymarketDeriveCredsRouteImport.update({
    id: '/api/polymarket/derive-creds',
    path: '/api/polymarket/derive-creds',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeckoterminalTokenDetailRoute =
  ApiGeckoterminalTokenDetailRouteImport.update({
    id: '/api/geckoterminal/token-detail',
    path: '/api/geckoterminal/token-detail',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGeckoterminalOhlcvRoute = ApiGeckoterminalOhlcvRouteImport.update({
  id: '/api/geckoterminal/ohlcv',
  path: '/api/geckoterminal/ohlcv',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeckoterminalMemesRoute = ApiGeckoterminalMemesRouteImport.update({
  id: '/api/geckoterminal/memes',
  path: '/api/geckoterminal/memes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCodexTokenRoute = ApiCodexTokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => ApiCodexRoute,
} as any)
const ApiCodexBaseTokensRoute = ApiCodexBaseTokensRouteImport.update({
  id: '/base-tokens',
  path: '/base-tokens',
  getParentRoute: () => ApiCodexRoute,
} as any)
const ApiCodexBarsRoute = ApiCodexBarsRouteImport.update({
  id: '/bars',
  path: '/bars',
  getParentRoute: () => ApiCodexRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/memes': typeof MemesRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/tokens': typeof TokensRoute
  '/api/codex': typeof ApiCodexRouteWithChildren
  '/api/hyperliquid': typeof ApiHyperliquidRoute
  '/asset/$identifier': typeof AssetIdentifierRoute
  '/api/codex/bars': typeof ApiCodexBarsRoute
  '/api/codex/base-tokens': typeof ApiCodexBaseTokensRoute
  '/api/codex/token': typeof ApiCodexTokenRoute
  '/api/geckoterminal/memes': typeof ApiGeckoterminalMemesRoute
  '/api/geckoterminal/ohlcv': typeof ApiGeckoterminalOhlcvRoute
  '/api/geckoterminal/token-detail': typeof ApiGeckoterminalTokenDetailRoute
  '/api/polymarket/derive-creds': typeof ApiPolymarketDeriveCredsRoute
  '/api/polymarket/events': typeof ApiPolymarketEventsRoute
  '/api/polymarket/history': typeof ApiPolymarketHistoryRoute
  '/api/polymarket/order': typeof ApiPolymarketOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/memes': typeof MemesRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/tokens': typeof TokensRoute
  '/api/codex': typeof ApiCodexRouteWithChildren
  '/api/hyperliquid': typeof ApiHyperliquidRoute
  '/asset/$identifier': typeof AssetIdentifierRoute
  '/api/codex/bars': typeof ApiCodexBarsRoute
  '/api/codex/base-tokens': typeof ApiCodexBaseTokensRoute
  '/api/codex/token': typeof ApiCodexTokenRoute
  '/api/geckoterminal/memes': typeof ApiGeckoterminalMemesRoute
  '/api/geckoterminal/ohlcv': typeof ApiGeckoterminalOhlcvRoute
  '/api/geckoterminal/token-detail': typeof ApiGeckoterminalTokenDetailRoute
  '/api/polymarket/derive-creds': typeof ApiPolymarketDeriveCredsRoute
  '/api/polymarket/events': typeof ApiPolymarketEventsRoute
  '/api/polymarket/history': typeof ApiPolymarketHistoryRoute
  '/api/polymarket/order': typeof ApiPolymarketOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/markets': typeof MarketsRoute
  '/memes': typeof MemesRoute
  '/perps': typeof PerpsRoute
  '/portfolio': typeof PortfolioRoute
  '/tokens': typeof TokensRoute
  '/api/codex': typeof ApiCodexRouteWithChildren
  '/api/hyperliquid': typeof ApiHyperliquidRoute
  '/asset/$identifier': typeof AssetIdentifierRoute
  '/api/codex/bars': typeof ApiCodexBarsRoute
  '/api/codex/base-tokens': typeof ApiCodexBaseTokensRoute
  '/api/codex/token': typeof ApiCodexTokenRoute
  '/api/geckoterminal/memes': typeof ApiGeckoterminalMemesRoute
  '/api/geckoterminal/ohlcv': typeof ApiGeckoterminalOhlcvRoute
  '/api/geckoterminal/token-detail': typeof ApiGeckoterminalTokenDetailRoute
  '/api/polymarket/derive-creds': typeof ApiPolymarketDeriveCredsRoute
  '/api/polymarket/events': typeof ApiPolymarketEventsRoute
  '/api/polymarket/history': typeof ApiPolymarketHistoryRoute
  '/api/polymarket/order': typeof ApiPolymarketOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/markets'
    | '/memes'
    | '/perps'
    | '/portfolio'
    | '/tokens'
    | '/api/codex'
    | '/api/hyperliquid'
    | '/asset/$identifier'
    | '/api/codex/bars'
    | '/api/codex/base-tokens'
    | '/api/codex/token'
    | '/api/geckoterminal/memes'
    | '/api/geckoterminal/ohlcv'
    | '/api/geckoterminal/token-detail'
    | '/api/polymarket/derive-creds'
    | '/api/polymarket/events'
    | '/api/polymarket/history'
    | '/api/polymarket/order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/markets'
    | '/memes'
    | '/perps'
    | '/portfolio'
    | '/tokens'
    | '/api/codex'
    | '/api/hyperliquid'
    | '/asset/$identifier'
    | '/api/codex/bars'
    | '/api/codex/base-tokens'
    | '/api/codex/token'
    | '/api/geckoterminal/memes'
    | '/api/geckoterminal/ohlcv'
    | '/api/geckoterminal/token-detail'
    | '/api/polymarket/derive-creds'
    | '/api/polymarket/events'
    | '/api/polymarket/history'
    | '/api/polymarket/order'
  id:
    | '__root__'
    | '/'
    | '/markets'
    | '/memes'
    | '/perps'
    | '/portfolio'
    | '/tokens'
    | '/api/codex'
    | '/api/hyperliquid'
    | '/asset/$identifier'
    | '/api/codex/bars'
    | '/api/codex/base-tokens'
    | '/api/codex/token'
    | '/api/geckoterminal/memes'
    | '/api/geckoterminal/ohlcv'
    | '/api/geckoterminal/token-detail'
    | '/api/polymarket/derive-creds'
    | '/api/polymarket/events'
    | '/api/polymarket/history'
    | '/api/polymarket/order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MarketsRoute: typeof MarketsRoute
  MemesRoute: typeof MemesRoute
  PerpsRoute: typeof PerpsRoute
  PortfolioRoute: typeof PortfolioRoute
  TokensRoute: typeof TokensRoute
  ApiCodexRoute: typeof ApiCodexRouteWithChildren
  ApiHyperliquidRoute: typeof ApiHyperliquidRoute
  AssetIdentifierRoute: typeof AssetIdentifierRoute
  ApiGeckoterminalMemesRoute: typeof ApiGeckoterminalMemesRoute
  ApiGeckoterminalOhlcvRoute: typeof ApiGeckoterminalOhlcvRoute
  ApiGeckoterminalTokenDetailRoute: typeof ApiGeckoterminalTokenDetailRoute
  ApiPolymarketDeriveCredsRoute: typeof ApiPolymarketDeriveCredsRoute
  ApiPolymarketEventsRoute: typeof ApiPolymarketEventsRoute
  ApiPolymarketHistoryRoute: typeof ApiPolymarketHistoryRoute
  ApiPolymarketOrderRoute: typeof ApiPolymarketOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tokens': {
      id: '/tokens'
      path: '/tokens'
      fullPath: '/tokens'
      preLoaderRoute: typeof TokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perps': {
      id: '/perps'
      path: '/perps'
      fullPath: '/perps'
      preLoaderRoute: typeof PerpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memes': {
      id: '/memes'
      path: '/memes'
      fullPath: '/memes'
      preLoaderRoute: typeof MemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/asset/$identifier': {
      id: '/asset/$identifier'
      path: '/asset/$identifier'
      fullPath: '/asset/$identifier'
      preLoaderRoute: typeof AssetIdentifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hyperliquid': {
      id: '/api/hyperliquid'
      path: '/api/hyperliquid'
      fullPath: '/api/hyperliquid'
      preLoaderRoute: typeof ApiHyperliquidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex': {
      id: '/api/codex'
      path: '/api/codex'
      fullPath: '/api/codex'
      preLoaderRoute: typeof ApiCodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/order': {
      id: '/api/polymarket/order'
      path: '/api/polymarket/order'
      fullPath: '/api/polymarket/order'
      preLoaderRoute: typeof ApiPolymarketOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/history': {
      id: '/api/polymarket/history'
      path: '/api/polymarket/history'
      fullPath: '/api/polymarket/history'
      preLoaderRoute: typeof ApiPolymarketHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/events': {
      id: '/api/polymarket/events'
      path: '/api/polymarket/events'
      fullPath: '/api/polymarket/events'
      preLoaderRoute: typeof ApiPolymarketEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/polymarket/derive-creds': {
      id: '/api/polymarket/derive-creds'
      path: '/api/polymarket/derive-creds'
      fullPath: '/api/polymarket/derive-creds'
      preLoaderRoute: typeof ApiPolymarketDeriveCredsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geckoterminal/token-detail': {
      id: '/api/geckoterminal/token-detail'
      path: '/api/geckoterminal/token-detail'
      fullPath: '/api/geckoterminal/token-detail'
      preLoaderRoute: typeof ApiGeckoterminalTokenDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geckoterminal/ohlcv': {
      id: '/api/geckoterminal/ohlcv'
      path: '/api/geckoterminal/ohlcv'
      fullPath: '/api/geckoterminal/ohlcv'
      preLoaderRoute: typeof ApiGeckoterminalOhlcvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/geckoterminal/memes': {
      id: '/api/geckoterminal/memes'
      path: '/api/geckoterminal/memes'
      fullPath: '/api/geckoterminal/memes'
      preLoaderRoute: typeof ApiGeckoterminalMemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/codex/token': {
      id: '/api/codex/token'
      path: '/token'
      fullPath: '/api/codex/token'
      preLoaderRoute: typeof ApiCodexTokenRouteImport
      parentRoute: typeof ApiCodexRoute
    }
    '/api/codex/base-tokens': {
      id: '/api/codex/base-tokens'
      path: '/base-tokens'
      fullPath: '/api/codex/base-tokens'
      preLoaderRoute: typeof ApiCodexBaseTokensRouteImport
      parentRoute: typeof ApiCodexRoute
    }
    '/api/codex/bars': {
      id: '/api/codex/bars'
      path: '/bars'
      fullPath: '/api/codex/bars'
      preLoaderRoute: typeof ApiCodexBarsRouteImport
      parentRoute: typeof ApiCodexRoute
    }
  }
}

interface ApiCodexRouteChildren {
  ApiCodexBarsRoute: typeof ApiCodexBarsRoute
  ApiCodexBaseTokensRoute: typeof ApiCodexBaseTokensRoute
  ApiCodexTokenRoute: typeof ApiCodexTokenRoute
}

const ApiCodexRouteChildren: ApiCodexRouteChildren = {
  ApiCodexBarsRoute: ApiCodexBarsRoute,
  ApiCodexBaseTokensRoute: ApiCodexBaseTokensRoute,
  ApiCodexTokenRoute: ApiCodexTokenRoute,
}

const ApiCodexRouteWithChildren = ApiCodexRoute._addFileChildren(
  ApiCodexRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MarketsRoute: MarketsRoute,
  MemesRoute: MemesRoute,
  PerpsRoute: PerpsRoute,
  PortfolioRoute: PortfolioRoute,
  TokensRoute: TokensRoute,
  ApiCodexRoute: ApiCodexRouteWithChildren,
  ApiHyperliquidRoute: ApiHyperliquidRoute,
  AssetIdentifierRoute: AssetIdentifierRoute,
  ApiGeckoterminalMemesRoute: ApiGeckoterminalMemesRoute,
  ApiGeckoterminalOhlcvRoute: ApiGeckoterminalOhlcvRoute,
  ApiGeckoterminalTokenDetailRoute: ApiGeckoterminalTokenDetailRoute,
  ApiPolymarketDeriveCredsRoute: ApiPolymarketDeriveCredsRoute,
  ApiPolymarketEventsRoute: ApiPolymarketEventsRoute,
  ApiPolymarketHistoryRoute: ApiPolymarketHistoryRoute,
  ApiPolymarketOrderRoute: ApiPolymarketOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
